version: '3'
services:
  ## nginx做静态资源服务和反向代理 #################################
  web1:
    image: nginx
    depends_on:
      - api
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/cert:/usr/share/nginx/cert
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
    ports:
      - "80:80"
    networks:
      - swarmNet
    deploy:
      mode: replicated
      replicas: 3
  ## tomcat运行java的web api ####################################
  web2:
     image: tomcat:8.5
     depends_on:
       - redis
     volumes:
       - ./webapp/server.xml:/usr/local/tomcat/conf/server.xml
       - ./webapp:/usr/local/tomcat/webapps
       - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
     ports:
      - "8080:8080"
     networks: 
       - swarmNet
     environment:
       - TZ=Asia/Shanghai
     deploy:
       mode: replicated
       replicas: 3
       resources:
         limits:
           memory: 512M
         reservations:
           memory: 256M
networks:
  swarmNet:
    driver: overlay
